function [descriptor] = pb_descriptor_eos__vdc_proto__VoxelDepthCorrection()
%pb_descriptor_eos__vdc_proto__VoxelDepthCorrection Returns the descriptor for message VoxelDepthCorrection.
%   function [descriptor] = pb_descriptor_eos__vdc_proto__VoxelDepthCorrection()
%
%   See also pb_read_eos__vdc_proto__VoxelDepthCorrection

  descriptor = struct( ...
    'name', 'VoxelDepthCorrection', ...
    'full_name', 'eos.vdc_proto.VoxelDepthCorrection', ...
    'filename', 'eos/storage/voxel_depth_correction.proto', ...
    'containing_type', '', ...
    'fields', [ ...
      struct( ...
        'name', 'start_depth', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.start_depth', ...
        'index', 1, ...
        'number', uint32(1), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0.5), ...
        'read_function', @(x) typecast(uint8(x), 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'depth_step', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.depth_step', ...
        'index', 2, ...
        'number', uint32(2), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0.5), ...
        'read_function', @(x) typecast(uint8(x), 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'shift_per_gmc_slope', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.shift_per_gmc_slope', ...
        'index', 3, ...
        'number', uint32(3), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0), ...
        'read_function', @(x) typecast(uint8(x), 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'starting_gmc_slope', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.starting_gmc_slope', ...
        'index', 4, ...
        'number', uint32(4), ...
        'type', uint32(2), ...
        'matlab_type', uint32(6), ...
        'wire_type', uint32(5), ...
        'label', uint32(1), ...
        'default_value', single(0), ...
        'read_function', @(x) typecast(uint8(x), 'single'), ...
        'write_function', @(x) typecast(single(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'correction_image_pngs', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.correction_image_pngs', ...
        'index', 5, ...
        'number', uint32(5), ...
        'type', uint32(12), ...
        'matlab_type', uint32(8), ...
        'wire_type', uint32(2), ...
        'label', uint32(3), ...
        'default_value', uint8([]), ...
        'read_function', @(x) uint8(x{1}(x{2} : x{3})), ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'sensor_serial_number', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.sensor_serial_number', ...
        'index', 6, ...
        'number', uint32(6), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'sensor_position', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.sensor_position', ...
        'index', 7, ...
        'number', uint32(7), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'camera_serial_number', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.camera_serial_number', ...
        'index', 8, ...
        'number', uint32(8), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'individual_sensor_calibration_time', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.individual_sensor_calibration_time', ...
        'index', 9, ...
        'number', uint32(9), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'camera_in_situ_calibration_time', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.camera_in_situ_calibration_time', ...
        'index', 10, ...
        'number', uint32(10), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'vdc_creation_time', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.vdc_creation_time', ...
        'index', 11, ...
        'number', uint32(11), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'vdc_creation_version', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.vdc_creation_version', ...
        'index', 12, ...
        'number', uint32(12), ...
        'type', uint32(9), ...
        'matlab_type', uint32(7), ...
        'wire_type', uint32(2), ...
        'label', uint32(1), ...
        'default_value', '0', ...
        'read_function', @(x) char(x{1}(x{2} : x{3}))', ...
        'write_function', @uint8, ...
        'options', struct('packed', false) ...
      ), ...
      struct( ...
        'name', 'fit_parameters', ...
        'full_name', 'eos.vdc_proto.VoxelDepthCorrection.fit_parameters', ...
        'index', 13, ...
        'number', uint32(13), ...
        'type', uint32(1), ...
        'matlab_type', uint32(5), ...
        'wire_type', uint32(1), ...
        'label', uint32(3), ...
        'default_value', double([]), ...
        'read_function', @(x) typecast(x, 'double'), ...
        'write_function', @(x) typecast(double(x), 'uint8'), ...
        'options', struct('packed', false) ...
      ) ...
    ], ...
    'extensions', [ ... % Not Implemented
    ], ...
    'nested_types', [ ... % Not implemented
    ], ...
    'enum_types', [ ... % Not Implemented
    ], ...
    'options', [ ... % Not Implemented
    ] ...
  );

  descriptor.field_indeces_by_number = java.util.HashMap;
  put(descriptor.field_indeces_by_number, uint32(1), 1);
  put(descriptor.field_indeces_by_number, uint32(2), 2);
  put(descriptor.field_indeces_by_number, uint32(3), 3);
  put(descriptor.field_indeces_by_number, uint32(4), 4);
  put(descriptor.field_indeces_by_number, uint32(5), 5);
  put(descriptor.field_indeces_by_number, uint32(6), 6);
  put(descriptor.field_indeces_by_number, uint32(7), 7);
  put(descriptor.field_indeces_by_number, uint32(8), 8);
  put(descriptor.field_indeces_by_number, uint32(9), 9);
  put(descriptor.field_indeces_by_number, uint32(10), 10);
  put(descriptor.field_indeces_by_number, uint32(11), 11);
  put(descriptor.field_indeces_by_number, uint32(12), 12);
  put(descriptor.field_indeces_by_number, uint32(13), 13);

